# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run build and tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --all --tags

      - name: Build and test with Gradle
        env:
          JAVA_OPTS: "-Xmx1024M"
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"
        run: ./gradlew  -Pversion=${{ github.ref_name }}-SNAPSHOT test build javadoc -s
